# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='items',
            new_name='item',
        ),
    ]
