# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productfeatured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfeatured',
            options={'verbose_name': 'Featured Product', 'verbose_name_plural': 'Featured Products'},
        ),
    ]
